# Generated by Django 5.1.6 on 2025-05-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
