# Generated by Django 5.1.6 on 2025-03-27 00:50

import businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/default_logo.png', null=True, upload_to=businesses.models.business_logo_path),
        ),
    ]
