# Generated by Django 5.1.6 on 2025-04-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_square_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='square_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
