# Generated by Django 5.1.6 on 2025-04-29 07:14

import businesses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_last_square_sync_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=businesses.models.business_logo_path),
        ),
    ]
