services:
  - name: backend
    type: web
    runtime: docker
    env: docker
    repo: https://github.com/heeran-kim/ai-marketer-v2-backend
    branch: dev
    plan: free
    dockerfilePath: backend/Dockerfile.render
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: USE_RENDER_DB
        value: "True"
      - key: TEMP_MEDIA_DISCORD_WEBHOOK
        value: "True"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://localhost:3000,https://ai-marketer-v2-frontend.vercel.app"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,0.0.0.0,backend-d6fz.onrender.com,ai-marketer-v2-frontend.vercel.app"
      - key: FRONTEND_BASE_URL
        value: "https://ai-marketer-v2-frontend.vercel.app"
      # Square API keys
      - key: SQUARE_ENV
        value: "sandbox"
      # - key: SQUARE_APP_ID_SANDBOX
      # value: "..."
      # - key: SQUARE_APP_SECRET_SANDBOX
      # value: "..."
      - key: SQUARE_BASE_URL_SANDBOX
        value: "https://connect.squareupsandbox.com"
      # - key: SQUARE_APP_ID_PROD
      # value: "..."
      # - key: SQUARE_APP_SECRET_PROD
      # value: "..."
      - key: SQUARE_BASE_URL_PROD
        value: "https://connect.squareup.com"
      - key: SQUARE_REDIRECT_URI
        value: "https://backend-d6fz.onrender.com/api/businesses/square/callback/"
      # Open AI API keys
      # - key: OPENAI_API_KEY
      # value: "..."
      # Discord API keys
      # - key: DISCORD_WEBHOOK_URL
      # value: "..."
      # Meta API keys
      # - key: FACEBOOK_APP_ID
      # value: "..."
      # - key: FACEBOOK_SECRET
      # value: "..."
      - key: FACEBOOK_REDIRECT_URI
        value: "https://ai-marketer-v2-frontend.vercel.app/settings/social/"
databases:
  - name: postgres
    plan: free
