# Generated by Django 5.1.6 on 2025-04-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='status',
        ),
    ]
