# Generated by Django 5.1.6 on 2025-04-05 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_logo'),
        ('promotions', '0002_remove_promotion_posts_remove_promotion_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotioncategories',
            options={'verbose_name_plural': 'Promotion Categories'},
        ),
        migrations.CreateModel(
            name='PromotionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='businesses.business')),
                ('categories', models.ManyToManyField(related_name='suggestions', to='promotions.promotioncategories')),
            ],
            options={
                'verbose_name_plural': 'Promotion Suggestions',
                'ordering': ['-created_at'],
            },
        ),
    ]
