# Generated by Django 5.1.6 on 2025-04-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_promotion_end_date_alter_promotion_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(),
        ),
    ]
