# Generated by Django 5.1.6 on 2025-05-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_alter_promotion_end_date_alter_promotion_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='product_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='product_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='promotionsuggestion',
            name='data_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionsuggestion',
            name='data_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionsuggestion',
            name='feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promotionsuggestion',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotionsuggestion',
            name='product_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='promotionsuggestion',
            name='product_names',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
