# Generated by Django 5.1.6 on 2025-05-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_promotion_product_data_promotion_product_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='sold_count',
        ),
    ]
