# Generated by Django 5.1.6 on 2025-04-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_last_square_sync_at_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesdatapoint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salesdatapoint',
            name='source',
            field=models.CharField(choices=[('upload', 'Uploaded File'), ('square', 'Square Sync')], default='upload', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesdatapoint',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salesdata'),
        ),
        migrations.AlterUniqueTogether(
            name='salesdatapoint',
            unique_together={('business', 'date', 'source')},
        ),
    ]
