# Generated by Django 5.1.6 on 2025-04-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_business_last_square_sync_at_and_more'),
        ('sales', '0002_alter_salesdatapoint_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesdatapoint',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salesdatapoint',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesdatapoint',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesdatapoint',
            name='units_sold',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='salesdatapoint',
            unique_together={('business', 'date', 'source', 'product_name', 'product_price')},
        ),
    ]
