# Generated by Django 5.1.6 on 2025-04-02 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_status'),
        ('promotions', '0002_remove_promotion_posts_remove_promotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='promotions.promotion'),
        ),
    ]
