# Generated by Django 5.1.6 on 2025-04-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.TextField(blank=True),
        ),
    ]
