# Generated by Django 5.1.6 on 2025-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
