# Generated by Django 5.1.6 on 2025-04-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_socialmedia_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='access_token',
        ),
    ]
