# Generated by Django 5.1.6 on 2025-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
