# Generated by Django 5.1.6 on 2025-03-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_requires_2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_2fa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
